- hosts: all
  become: true
  tasks:
    - name: Creating app dir
      file:
        path: /app
        state: directory
    - name: Creating .env
      template:
        src: ../templates/.env.template
        dest: /app/.env
    - name: Running container
      docker_container:
        name: redmine
        image: redmine
        detach: yes
        restart_policy: always
        pull: true
        ports:
          - "8080:3000"
        env_file: /app/.env
